function initPopup() {
    const input = document.querySelector("#sttUsernameInput") as HTMLInputElement;
    input?.addEventListener("change", () => {
        localStorage.setItem("username", input.value);
    });
    input.value = localStorage.getItem("username") ?? "";
}

initPopup();

// /*
// This has been generated by the overpass-turbo wizard.
// The original search was:
// “railway=platform_edge or railway=platform in innviertel”
// */
// [out:json][timeout:25];
// // gather results
// (
// 	nwr["railway"="platform_edge"]["ref"="1"](around:50,48.191698,13.128855);
// 	nwr["railway"="platform"]["ref"="1"](around:50,48.191698,13.128855);
// );
// // print results
// (._;>;);
// out;